version: '2.4'

services:
  web:
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    #   args:
    #     STATIC_URL: '/static/'
    image: art9studio/jumblesweets.backend:latest
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - postgres
      - redis
      - search
    # command: uwsgi /app/saleor/wsgi/uwsgi.ini

  postgres:
    image: library/postgres:10.5
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql
    ports:
      - 5432:5432


  redis:
    image: library/redis:latest
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data
    ports:
      - 6379:6379
    # command: redis-server --requirepass

  # celery:
  #   # build:
  #   #   context: .
  #   #   dockerfile: ./Dockerfile
  #   #   args:
  #   #     STATIC_URL: '/static/'
  #   command: celery -A saleor worker --app=saleor.celeryconf:app --loglevel=info
  #   restart: unless-stopped
  #   networks:
  #     - saleor-backend-tier
  #   volumes:
  #     - .:/app:Z
  #   env_file: .env
  #   depends_on:
  #     - redis

  search:
    image: elasticsearch:6.4.2
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-search:/usr/share/elasticsearch/
    # ports:
    #   - 9200:9200
    # See https://github.com/docker/compose/issues/4513 if updating to version '3'
    mem_limit: 256m
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m -Dlog4j2.disable.jmx=true"

  caddy:
    image: abiosoft/caddy:0.11.0
    volumes:
      - jumble-caddy:/root/.caddy
      - ./Caddyfile:/etc/Caddyfile
    networks:
      - saleor-backend-tier
    env_file:
      - ./.env
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    restart: unless-stopped

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-search:
    driver: local
  jumble-caddy:
    driver: local

networks:
  saleor-backend-tier:
    driver: bridge
