# Generated by Django 2.1.2 on 2018-10-31 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_auto_20181027_2128'),
        ('checkout', '0015_auto_20181017_1346'),
    ]

    operations = [
    ]
