# Generated by Django 2.1.2 on 2018-10-31 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0065_auto_20181027_2128'),
        ('order', '0066_auto_20181023_0319'),
    ]

    operations = [
    ]
