# Generated by Django 2.1.2 on 2018-10-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0077_auto_20181027_2128'),
        ('account', '0023_auto_20180719_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='user_favourites', to='product.Product'),
        ),
    ]
